### ISSUE TITLE
sock permission denied

### ISSUE THREAD

**Issue by OUZYcn** [golift/telegraf-docker#43]
Need your suggestion to fix this issue. 

Error log
`2023-04-14T06:48:00Z E! [inputs.docker] Error in plugin: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?filters=%7B%22status%22%3A%7B%22running%22%3Atrue%7D%7D": dial unix /var/run/docker.sock: connect: permission denied`

docker-composer
```
version: “3.8”
services:
  telegraf:
      image: golift/telegraf
      container_name: telegraf
      restart: unless-stopped
      user: telegraf:1100 -->1101 (docker gid)
      volumes:
        - /abc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
```

Edit 1: it works if 1100 changed 1101
